### ISSUE TITLE
Confgen consul-template module.

### ISSUE THREAD

**Issue by eddwardo** [fieldaware/confgen#8]
When using confgen with consul-template and git2consul, `consul-template.cfg` might be auto-generated. It (consul-template.cfg) should be available for each node with configuration files for the services. Such as:
```
.
└── cluster
    └── server
        └── service_name
            ├── config1.ini.ctmpl
            └── config2.ini.ctmpl
            └── consul-template.cfg
```

This module should be optional in usage.

**Comment by fieldawarepiotr** [comment]
Won't do.
